Feature/dark theme
swaponline/swap.io-keys pull request #48
Opened 2021-09-02 08:42 UTC by Denisfront

2021-09-03 04:40 UTC, tany31 commented on src/messageHandler.ts
> +          break
А зачем тут промис используется?

2021-09-06 03:43 UTC, Denisfront commented on src/messageHandler.ts
> +          break
При инициализации приложения необходимо дождаться пока отработает `messageHandler`

Дальше по коду выглядит так

```
  async mounted() {
    await messageHandler()
    this.setAppTheme()
  },
```

2021-09-06 04:36 UTC, alexeyvokin requested changes

2021-09-06 04:36 UTC, alexeyvokin commented on src/assets/scss/_theme-variable.scss
> +  --additional-button-background: #212f46;
для темной темы не стали выносить цвета в переменные (по сути, палитру цветов сайта)?

2021-09-06 04:36 UTC, alexeyvokin commented on src/assets/scss/base.scss
> +@import 'theme-variable';
тултип не стилизуется относительно светлой/темной темы?

я к тому, что, возможно, стоит тему импортировать перед импортом стилей для тултипов?

2021-09-06 04:36 UTC, alexeyvokin commented on src/messageHandler.ts
> +        case SET_APP_THEME:
`SET_APP_THEME`

возможно, имеет смысл вынести из файла констант темы в файл констант (по сути - типов) сообщений

2021-09-06 04:36 UTC, alexeyvokin commented on src/utils/theme.ts
> +}
1) мб, стоит рассмотреть at-правило `@supports`, чтобы игнорировать выбор опции темы как "системная"
2) я думаю, есть смысл сделать matches как observable, и менять текущую тему при смене системного значения (чтобы добиться автоматического перехода цветовой темы, при смене дня/ночи, сейчас будет работать только после перезагрузки, как я понял)

2021-09-06 04:36 UTC, alexeyvokin commented on src/App.vue
> +    await messageHandler()
есть, кстати, вариант, не монтировать приложение, пока не установятся обработчики

```
messageHandler().then(() => {
  app.mount('#app') // or new Vue({ /* options */ }).mount('#app')
})
```

2021-09-07 10:12 UTC, shendel commented on src/messageHandler.ts
> +          break
тогда может лучше 
`
 messageHandler().then((result) => { this.setAppTheme() })
`
чтобы не блокировать mounted, а по умолчанию показывать что-то дефолтное. Не будет фризов при ожидании ответа?

2021-09-08 04:44 UTC, alexeyvokin commented on src/messageHandler.ts
> +          break
блокирования не должно случиться, т.к. функция встанет в очередь микрозадач. messageHandler выполнится, но браузер не будет дожидаться выполнения этой микрозадачи, т.е. будет то же самое, что и в случае с `messageHandler().then((result) => { this.setAppTheme() })`

2021-09-20 12:13 UTC, Denisfront commented on src/App.vue
> +    await messageHandler()
Пока такая реализация не работает, оставил TODO, чтобы разобраться в будущем

2021-09-20 12:24 UTC, Denisfront commented on src/utils/theme.ts
> +}
Оставил TODO, пока есть более приоритетные задачи

2021-09-21 02:49 UTC, alexeyvokin approved these changes

2021-09-21 06:54 UTC, merged